#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Chip8Android.Resource", IsApplication=true)]

namespace Chip8Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sample_0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sample_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sample_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sample_3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_7 = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int button0 = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button3 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int button4 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int button5 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int button6 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int button7 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int button8 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int button9 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int buttonA = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int buttonB = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int buttonC = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int buttonD = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int buttonE = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int buttonF = 2131034128;
			
			// aapt resource value: 0x7f050000
			public const int chip8view = 2131034112;
			
			// aapt resource value: 0x7f050011
			public const int view1 = 2131034129;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int test = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
